update some music scripts to be a little more legible an harmonized with my new style of doing things

diff --git a/2artless b/2artless
--- a/2artless
+++ b/2artless
@@ -1,14 +1,9 @@
 #!/bin/bash
-#a bash script to make the flac gooder
+set -euo pipefail #bash strict mode
+[ "$#" -eq 0 ] && echo USAGE: "$0 files_to_remove_embedded_art_from..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
 #removes embedded album art
 #and is bit exact
-for i in *.flac ; do
-    ffmpeg -i "$i" -acodec copy -fflags +bitexact -vn "$(basename "${i/.flac}")..flac"
+for i in "$@" ; do
+  ffmpeg -i "$i" -acodec copy -fflags +bitexact -vn tmp.artless."$i"
+  mv tmp.artless."$i" "$i"
 done
-for i in *.mp3 ; do
-    ffmpeg -i "$i" -acodec copy -fflags +bitexact -vn "$(basename "${i/.mp3}")..mp3"
-done
-for i in *.m4a ; do
-    ffmpeg -i "$i" -acodec copy -fflags +bitexact -vn "$(basename "${i/.m4a}")..m4a"
-done
-rename -f "s/\.\././" *
diff --git a/mmusic-transfer b/mmusic-transfer
--- a/mmusic-transfer
+++ b/mmusic-transfer
@@ -1,17 +1,21 @@
 #!/bin/bash
-# this script called by the populate-mmusic-dir command
-# takes two arguments:
-# 1: the file we are transfering from
-# 2: the file we are transfering to (will end with the same extension as 1)
-if ! ([[ -f "$2" ]] || [[ -f "$2.m4a" ]])
+set -euo pipefail #bash strict mode
+[ "$#" -ne 2 ] && echo USAGE: "$0 from_file to_file" && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
+
+# This script is called by the populate-mmusic-dir command
+# This script takes two arguments:
+# 1: the file we are transferring from
+# 2: the file we are transferring to (as passed in, ends with the same file name and extension as 1, but living in a different file path)
+
+if ! ([[ -f "$2" ]] || [[ -f "$2.m4a" ]]) #if something's already there, don't bother to copy.
 then
-    d=`dirname "$2"`
-    [[ -d "$d" ]] || mkdir -p "$d"
-    if [ "${1: -4}" = ".mp3" ] || [ "${1: -4}" = ".m4a" ]
-    then
-	cp -n "$1" "$2" && echo "$2"
-    else
-	ffmpeg -loglevel error -n -i "$1" -vn "$2.m4a" && echo "$2.m4a"
-    fi
+  d=`dirname "$2"`
+  [[ -d "$d" ]] || mkdir -p "$d"
+  if [ "${1: -4}" = ".mp3" ] || [ "${1: -4}" = ".m4a" ] #if it's already mp3 or m4a, just copy; otherwise, convert to m4a 
+  then
+    cp -n "$1" "$2" && echo "$2"
+  else
+    ffmpeg -loglevel error -n -i "$1" -vn "$2.m4a" && echo "$2.m4a"
+  fi
 fi
 
diff --git a/populate-mmusic-dir b/populate-mmusic-dir
--- a/populate-mmusic-dir
+++ b/populate-mmusic-dir
@@ -1,23 +1,28 @@
 #!/bin/bash
-# this script copies music files from the current dir to a different dir (specified as an argument, defaults to "../../mmusic/", you probably want to pass in /mnt/e/mmusic/ if you're me)
-# and re-encodes non-mp3/m4as to be mp3s
+set -euo pipefail #bash strict mode
+[ "$#" -eq 0 ] && echo USAGE: "$0 path_to_dir_to_populate_with_music paths_to_copy_and_convert_into_that_dir..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
 
-# by default, this script does not clobber, in order to save time
-# if you'd like to override this behavior, remove the "-n"s from mmusic-transfer
-# but it would likely be more prudent to simply rm the mmusic dir beforehand
+# This script copies music files from the current dir to a different dir (specified as an argument, I find "../../mmusic/" and "/mnt/e/mmusic/" quite useful sometimes)
+# and re-encodes non-mp3/m4as to be m4as using mmusic-transfer.
 
-# this script might take an hour or two to run, on my computer and collection
+# By default, this script does not clobber, in order to save time.
+# If you'd like to override this behavior, remove the "-n"s from mmusic-transfer.
+# However, it would likely be more prudent to simply rm the mmusic dir beforehand
 
-# this script does not copy images of any kind, to save space
+# This script might take an hour or two to run, on my computer and collection.
 
-mdir=${1:-"../../mmusic"}/ # an extra slash is harmless but a missing one is bad
+# This script does not copy images of any kind, to save space (but images embedded in the metadata of m4a/mp3s may be preserved).
 
-# it is not necessary to explicitly filter out these invalid files
-# but it does speed up the process a bit, probably
-find . -type f \
-	-not -name "*.png" -not -name "*.jpg" -not -name "*.gif" \
-	-not -name "*.log" -not -name "*.cue" -not -name "*.m3u" \
-	-not -name "*.txt" -not -name "*.pdf" -not -name "*.doc" \
-	-not -name "*.db" -not -name "*.ini"  \
-	-print0 | \
-	xargs -0 -P 8 -I % mmusic-transfer "%" "$mdir%"
+mdir="$1"/ # an extra slash is harmless but a missing one is bad
+shift
+for i in "$@"; do
+# It is not necessary to explicitly filter out these invalid file types,
+# but it does speed up the process a bit, probably.
+  find "$i" -type f \
+    -not -name "*.png" -not -name "*.jpg" -not -name "*.gif" \
+    -not -name "*.log" -not -name "*.cue" -not -name "*.m3u" \
+    -not -name "*.txt" -not -name "*.pdf" -not -name "*.doc" \
+    -not -name "*.db" -not -name "*.ini"  \
+    -print0 | \
+    xargs -0 -P 8 -I % mmusic-transfer "%" "$mdir%"
+done
