misc improvements. some of these scripts might not work

diff --git a/crack-audible b/crack-audible
--- a/crack-audible
+++ b/crack-audible
@@ -1,6 +1,6 @@
 #!/bin/bash
 #set -euo pipefail #no bash strict mode, so the 0x0"$2" trick works
-[ "$#" -eq 0 ] || [ "$#" -gt 2 ] && echo USAGE: "$0 arguments..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
+[ "$#" -eq 0 ] || [ "$#" -gt 3 ] && echo USAGE: "$0 aax_file [key_to_start_trying_at (default:0) [key_to_stop_trying_at (default:0xFFFFFFFF)]]" && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
 
 # Please only use this software legally in your country (such as personal use, where applicable)!
 # So, this is actually a pretty bad way to crack this encryption, because using a bash loop to repeatedly call ffmpeg (in sequence!) is prety slow, due to the associated overhead.
@@ -10,9 +10,12 @@
 # As such, the correct execution of this program has remained theoretical.
 
 key=0x0"$2" #lets you pass in a key to start at (for instance, your known key, your last attempt, or an offset you are parallelizing on) as optional second argument (takes hex string with no prefix, defaults to 0)
+maxnum=${3:-0xFFFFFFFF}
+
 until ffmpeg -loglevel panic -activation_bytes $(printf '%08X' $key) -i "$1" -c copy "$1".m4a
 do
   printf '%08x\r' $key #The \r is a carriage return, thus the line in the terminal overwrites itself, making a dynamic counter.
+  [[ $key -gt "$maxnum" ]] && echo "Key test value has exceeded the maximum, $maxnum; program is quitting unsuccessfully!" && exit 1
   ((key++))
 done
 echo $(printf '%08x' $key) >"aax key.txt"
diff --git a/vid-excerpt b/vid-excerpt
--- a/vid-excerpt
+++ b/vid-excerpt
@@ -1,5 +1,6 @@
 #!/bin/bash
-#usage: vid-excerpt infilename time-begin (time-end (outfilename (additional options for ffmpeg)))
+set -euo pipefail #bash strict mode
+[ "$#" -lt 2 ] && echo USAGE: "$0 infilename time-begin [time-end [outfilename [additional options for ffmpeg...]]]" && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
 outfile=${4:-vid-excerpt."$1"}
 if [ "$#" -ge 3 ]; then
   ffmpeg -ss "$2" -i "$1" -to "$3" -c copy -copyts ${@:5} "$outfile"
diff --git a/youtube-format-munge-720 b/youtube-format-munge-720
--- a/youtube-format-munge-720
+++ b/youtube-format-munge-720
@@ -1,6 +1,22 @@
+#!/bin/bash
+# set -euo pipefail #bash strict mode
+[ "$#" -lt 1 ] && echo USAGE: "$0 infiles..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
+
 #you can scale DVDs to 720p for youtube.
 #I used to use truly lossless crf 0 for this but it's just not worth the space. All the things I use this on are already rips.
-ffmpeg -i "$1" -c:a copy -vf "scale=w=1280:h=720:force_original_aspect_ratio=decrease" -c:v libx264 -crf 16 -preset fast 720d."$1".mkv
+
+mkdir -p output
+
+for i in "$@"; do
+  #For some reason these have a trailing carriage return on them? Whatever; we just strip that, instead of trying to find the needle in the ffprobe documentation haystack that lets us turn off this anti-feature.
+  width=`ffprobe -v error -select_streams v -show_entries stream=width -of csv=p=0:s=x "$i" | tr -d '\r'`
+  height=`ffprobe -v error -select_streams v -show_entries stream=height -of csv=p=0:s=x "$i" | tr -d '\r'`
+  echo $width×$height: $i
+  ffmpeg -i "$i" -c:a copy -vf "scale=w=1280:h=1050" -c:v libx264 -crf 16 -preset fast output/"$i".mp4
+done
+
+cd output
+vid-cat output.mp4 "$@"
 
 # Experiment on a video that is I guess wider than 16:9 (Video resolution: 702x576) (In fact, 16/9 = 1.77..., 4/3 = 1.33..., 702/576 = 1.21875, 5/4 = 1.25)
 # scale=w=1280:h=720:force_original_aspect_ratio=increase Video resolution: 1280x1050
@@ -8,3 +24,6 @@ ffmpeg -i "$1" -c:a copy -vf "scale=w=1280:h=720:force_original_aspect_ratio=dec
 # scale=w=1280:h=-2:force_original_aspect_ratio=increase Video resolution: 1280x1050
 # scale=w=1280:h=720:force_original_aspect_ratio=decreaseVideo resolution: 878x720
 #IDK what I would do if I needed to avoid FFMPEG (libx264) "height not divisible by 2" AND I didn't know which slot should have the -2 in it...
+
+# -f mp4 pipe:1 | youtubeuploader -filename -
+# -f concat -i vidlist.tmp.txt
