standardize and massage the ocr-pdf stuff

diff --git a/tessall b/tessall
--- a/tessall
+++ b/tessall
@@ -1,4 +1,8 @@
-for i in *
+#!/bin/bash
+set -euo pipefail #bash strict mode
+[ "$#" -eq 0 ] && echo USAGE: "$0 arguments..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
+
+for i in "$@"
 do
   echo "$i"
   tesseract "$i" stdout --psm 1 --dpi 150 >>tess.txt
