have text handle unfound commands better
used to be it would just run cat with no args, which cats stdin interactively, confusingly

diff --git a/text b/text
--- a/text
+++ b/text
@@ -2,5 +2,10 @@
 set -euo pipefail #bash strict mode
 [ "$#" -eq 0 ] && echo USAGE: "$0 commands_to_print_the_text_of..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
 for i in "$@" ; do
-  cat `whereis $i | cut -d ':' -f 2`
+  target=`whereis $i | cut -d ':' -f 2 | sed -e 's/^[[:space:]]*//'` #this removes lreading whitespace
+  if [ -z "$target" ] ; then
+    echo "$i not found by whereis" 1>&2
+  else
+    cat "$target"
+  fi
 done
