enhancements to text
1. no longer prints ''cat: 'x:': No such file or directory'' at the beginning\n\n2. can take any number of arguments (i doubt i will ever use this, but if i ever want to... it's there)\n\n3. if given 0 arguments, will print usage message and return error code

diff --git a/text b/text
--- a/text
+++ b/text
@@ -1,2 +1,6 @@
 #!/bin/bash
-cat `whereis $1`
+set -euo pipefail #bash strict mode
+[ "$#" -eq 0 ] && echo USAGE: "$0 commands_to_print_the_text_of..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
+for i in "$@" ; do
+  cat `whereis $i | cut -d ':' -f 2`
+done
