totally fix youtube-dl-part

diff --git a/youtube-dl-part b/youtube-dl-part
--- a/youtube-dl-part
+++ b/youtube-dl-part
@@ -1,12 +1,21 @@
 #!/bin/bash
 set -euo pipefail #bash strict mode
-[ "$#" -lt 2 ] || [ "$#" -gt 3 ] && echo USAGE: "$0 target-url starting-timestamp [ending-timestamp]" && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
+[ "$#" -lt 2 ] && echo USAGE: "$0 target-url starting-timestamp [ending-timestamp [additional_arguments...]]" && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
 
-b="$(basename $1)"
-if [ $# -eq 3 ]; then
-  optional_to_param="-to ${3@Q}"
+target_url="$1"
+starting_timestamp="$2"
+b="$(basename $target_url)"
+if [ $# -ge 3 ]; then
+  optional_to_param="-to $3"
+  shift 3
 else
   optional_to_param=""
+  shift 2
 fi
-# The cut command here is only needed because yt-dlp -g returns two urls, which are separated by a newline. I don't really know why, nor what that means, nor if it always happens, or what. I pick the first one arbitrarily. #edit: this seems to be video and then audio
-ffmpeg -ss "$2" -i $(yt-dlp -g "$1" | cut -d $'\n' -f1) $optional_to_param -c copy -copyts "${b##*=}.youtube-dl-part.mp4"
+
+# Sometimes we get one url, and sometimes two (video and then audio). This should handle both. NB: It's actually important that you *don't* quote the $() expression here.
+inputs=""
+for url in $(yt-dlp -g "$target_url") ; do
+  inputs="$inputs -ss $starting_timestamp -i $url $optional_to_param"
+done
+quine ffmpeg $inputs -c copy -copyts "${b##*=}.youtube-dl-part.mp4" "$@"
